# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Artist.create(id: 1, name: 'RAISE A SUILEN')
Album.create(id: 1, artist_id: 1, name: 'R·I·O·T', released_at: '2018-12-12')
Album.create(id: 2, artist_id: 1, name: 'A DECLARATION OF xxx', released_at: '2019-2-20')
Album.create(id: 3, artist_id: 1, name: 'Invincible Fighter', released_at: '2019-6-19')
Album.create(id: 4, artist_id: 1, name: 'DRIVE US CRAZY', released_at: '2020-1-22')
Album.create(id: 5, artist_id: 1, name: 'ERA', released_at: '2020-8-19')
Album.create(id: 6, artist_id: 1, name: 'Sacred world', released_at: '2020-10-21')
Album.create(id: 7, artist_id: 1, name: 'mind of prominence', released_at: '2021-1-27')
Album.create(id: 8, artist_id: 1, name: 'EXIST', released_at: '2021-4-21')
Album.create(id: 100, artist_id: 1, name: 'THE THIRD(仮) 1st ライブ', released_at: '2018-09-26')
Album.create(id: 101, artist_id: 1, name: 'バンドリ！ ガールズバンドパーティ！ カバーコレクションVol.3', released_at: '2019-12-18')
Album.create(id: 102, artist_id: 1, name: 'バンドリ！ ガールズバンドパーティ！ カバーコレクションVol.4', released_at: '2020-05-27')
Album.create(id: 103, artist_id: 1, name: 'バンドリ！ ガールズバンドパーティ！ カバーコレクションVol.5', released_at: '2021-02-24')
Album.create(id: 104, artist_id: 1, name: 'バンドリ！ ガールズバンドパーティ！ カバーコレクションVol.6', released_at: '2021-11-10')
Song.create(id: 1, artist_id: 1, album_id: 1, name: 'R·I·O·T')
Song.create(id: 2, artist_id: 1, album_id: 1, name: 'UNSTOPPABLE')
Song.create(id: 3, artist_id: 1, album_id: 2, name: 'A DECLARATION OF xxx')
Song.create(id: 4, artist_id: 1, album_id: 2, name: "EXPOSE 'Burn out!!!'")
Song.create(id: 5, artist_id: 1, album_id: 3, name: 'Invincible Fighter')
Song.create(id: 6, artist_id: 1, album_id: 3, name: "Takin'my Heart")
Song.create(id: 7, artist_id: 1, album_id: 4, name: 'DRIVE US CRAZY')
Song.create(id: 8, artist_id: 1, album_id: 4, name: 'HELL! or HELL?')
Song.create(id: 9, artist_id: 1, album_id: 5, name: 'Invincible Fighter')
Song.create(id: 10, artist_id: 1, album_id: 5, name: 'A DECLARATION OF xxx')
Song.create(id: 11, artist_id: 1, album_id: 5, name: 'SOUL SOLDIER')
Song.create(id: 12, artist_id: 1, album_id: 5, name: 'UNSTOPPABLE')
Song.create(id: 13, artist_id: 1, album_id: 5, name: 'HELL! or HELL?')
Song.create(id: 14, artist_id: 1, album_id: 5, name: 'Beautiful Birthday')
Song.create(id: 15, artist_id: 1, album_id: 5, name: "Takin'my Heart")
Song.create(id: 16, artist_id: 1, album_id: 5, name: 'DRIVE US CRAZY')
Song.create(id: 17, artist_id: 1, album_id: 5, name: '!NVADE SHOW!')
Song.create(id: 18, artist_id: 1, album_id: 5, name: 'REIGNING')
Song.create(id: 19, artist_id: 1, album_id: 5, name: "EXPOSE 'Burn out!!!'")
Song.create(id: 20, artist_id: 1, album_id: 5, name: 'R·I·O·T')
Song.create(id: 21, artist_id: 1, album_id: 6, name: 'Sacred world')
Song.create(id: 22, artist_id: 1, album_id: 7, name: 'mind of prominence')
Song.create(id: 23, artist_id: 1, album_id: 7, name: 'JUST THE WAY I AM')
Song.create(id: 24, artist_id: 1, album_id: 8, name: 'EXIST')
Song.create(id: 25, artist_id: 1, album_id: 8, name: 'Embrace of light')
Song.create(id: 26, artist_id: 1, album_id: 8, name: 'OUTSIDER RODEO')
Song.create(id: 27, artist_id: 1, album_id: 100, name: 'That Is How I Roll!')
Song.create(id: 28, artist_id: 1, album_id: 100, name: 'しゅわりん☆どり～みん')
Song.create(id: 29, artist_id: 1, album_id: 100, name: 'パスパレボリューションず☆')
Song.create(id: 30, artist_id: 1, album_id: 100, name: 'えがおのオーケストラっ！')
Song.create(id: 31, artist_id: 1, album_id: 100, name: "Don't be afraid!")
Song.create(id: 32, artist_id: 1, album_id: 100, name: 'ゆら・ゆらRing-Dong-Dance')
Song.create(id: 33, artist_id: 1, album_id: 100, name: 'Hey-Day狂騒曲（カプリチオ）')
Song.create(id: 34, artist_id: 1, album_id: 100, name: 'Scarlet Sky')
Song.create(id: 35, artist_id: 1, album_id: 100, name: 'ゴーカ！ごーかい！？ファントムシーフ！')
Song.create(id: 36, artist_id: 1, album_id: 100, name: 'R·I·O·T')
Song.create(id: 37, artist_id: 1, album_id: 101, name: '激動')
Song.create(id: 38, artist_id: 1, album_id: 101, name: '1/3の純情な感情')
Song.create(id: 39, artist_id: 1, album_id: 102, name: 'ヒトリノ夜')
Song.create(id: 40, artist_id: 1, album_id: 103, name: '恋しさとせつなさと心強さと')
Song.create(id: 41, artist_id: 1, album_id: 103, name: 'SAVIOR OF SONG')
Song.create(id: 42, artist_id: 1, album_id: 104, name: 'CORE PRIDE')
Song.create(id: 43, artist_id: 1, album_id: 104, name: 'DEPARTURES')
Song.create(id: 44, artist_id: 1, album_id: 104, name: 'DAYBREAK FRONTLINE')
